#Input & Output folders
INPUT=INPUT/
OUTPUT= OUTPUT/
SUCCESS=SUCCESS/
FAILURE=FAILURE/
CONFIRMED_DUPLICATE=CONFIRMED_DUPLICATE/
Temp = Temp/

CopyOfOutput=OUTPUT_COPY/
CopyOfEncryptedOutput = CopyOfEncryptedOutput/
AuditLog= log/

ListOfMerchantIdForBrunei=ListOfCodesForbrunei.xlsx


#Pgp Encryption Details
#(JUST_ENCRYPT_N_UPLOAD --> will encrypt whatever files placed in INPUT folder & upload it based on UPLOAD_FILES_TO_SFTP Flag)
JUST_ENCRYPT_N_UPLOAD =N
PGP_ENCRYPTION_REQUIRED=N
PGP_PUBLIC_KEY_PATH = /home/bznpwrusr/AmwayProjects/Amway_In/KEY/AmwayQAPublicKey.asc
#PGP_PUBLIC_KEY_PATH=/home/bznpwrusr/AmwayProjects/Amway_In/KEY/AmwayLivePublicKey.asc

#SFTP server details
UPLOAD_FILES_TO_SFTP= N
SFTP_HOST= 	sftp-dev.amway.com
SFTP_PORT=	22
SFTP_TIME_OUT=	60
SFTP_USERNAME=	USJFDF7
SFTP_PASSWORD=	Rp4s5M8WaEd6r3
SFTP_SERVER_UPLOAD_FOLDER_PATH = ./apac/inbound/

UploadUsingJSCH=N
#Organize Files After Processing (Based on File Create Date)
ENABLE_FILE_ORGANIZER = N
FILES_PICKUP_PATH = /home/bznpwrusr/Desktop/Amway_Test/Amway_Czech/SUCCESS/ 
FILES_DROP_PATH = /home/bznpwrusr/Desktop/Amway_Test/Amway_Czech/Amway_APAC_LIVE/


ENABLE_MAIL_NOTIFICATION = N
TYPE_OF_ENCRYPTION = OPEN
MAIL_HOST = smtp.office365.com
MAIL_PORT = 587
MAIL_FROM = no-reply@byzan.com
MAIL_PASSWORD = Byzan!@#123
MAIL_TO = supriya.m@byzan.com
MAIL_CC = ripson.byzan@gmail.com
MAIL_SUBJECT = Files failed in Processing : Amway Japan
INCLUDE_ATTACHMENT_IN_MAIL = N

ENABLE_DUPLICATE_FILE_CHECK=Y
#Local Mysql db
Host = jdbc:mysql://localhost:3306/Amway_Dashboard
port = 3306
#userName is nothing but database name
userName = Amway_Dashboard 
userId = root
password =root

#UAT Mysql db
#Host = bzn-dbsvr-02.cpsxrip4w7jl.ap-south-1.rds.amazonaws.com
#Host = jdbc:mysql://bzn-dbsvr-02.cpsxrip4w7jl.ap-south-1.rds.amazonaws.com:3306/bzn-dbsvr-02-shm-uat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#port = 3306
#userName = bzn-dbsvr-02-shm-uat
#userId = BZNDBUATUSR
#password = m^EY!CG1o84L

#Database to check Duplicate Files > 1.Y 2.N
#ENABLE_DUPLICATE_FILE_CHECK=Y
#Host = bznamwy.cpsxrip4w7jl.ap-south-1.rds.amazonaws.com
#port = 1521
#userName = BZNAMWY
#userId = BZNadmin
#password = Byzan321#2!
