UniqueApplicationId=FetchMailAttachmentMainCzech

EMAIL_EXTRACTION_PATH=../Amway_Czech/INPUT/

MAIL_CONFIGURATION_MASTER=EmailConfigurationMaster.xls

FILE_NAMING_COUNTER_REQ=N

FILE_NAMING_COUNTER_PATH=FileNamingCounter.txt

MAIL_SENTDATE_FILENAMES=MailSentDateNFileNmaes.properties

LATEST_TO_OLDER=N

SCAN_MAILS_FOR_PARTICULAR_DATE=N

INPUT_DATE=22/03/2023

GET_ONLY_UNREAD_MAILS=Y

RESET_FILE_COUNTER=month

ALLOWED_FILE_EXTENSION=
PROHIBITED_FILE_EXTENSION=jpeg,jpg,tiff,gif,pdf,png

DETAIL_LOGGING_REQ=Y

EXECUTE_FILE_CONVERTER=Y

FILE_CONVERTER_PATH=../Amway_Czech/CRun.sh
