UniqueApplicationId=FetchMailAttachmentMainCzech

#Email extraction folder path
EMAIL_EXTRACTION_PATH = /home/bznpwrusr/Desktop/Amway_Test/Amway_Czech/INPUT/
# Mail configuration master
MAIL_CONFIGURATION_MASTER = /home/bznpwrusr/Desktop/Amway_Test/Mail_Czech/EmailConfigurationMaster.xls

#File Naming Counter (City MT940 Files)
FILE_NAMING_COUNTER_REQ = N
FILE_NAMING_COUNTER_PATH = /home/ubuntu/Amway_Czech/Mail_Czech/FileNamingCounter.txt

#Mapping of Filenames & Mailfetch date
MAIL_SENTDATE_FILENAMES = /home/bznpwrusr/Desktop/Amway_Test/Mail_Czech/MailSentDateNFileNmaes.properties

# Mail fetch order
LATEST_TO_OLDER = N

#Scan mails for particular date
SCAN_MAILS_FOR_PARTICULAR_DATE = N
INPUT_DATE = 22/03/2023

#Getting only Unread mails
GET_ONLY_UNREAD_MAILS = Y

#File Counter Reset (day OR month OR year)
RESET_FILE_COUNTER = month

#File Filter & Mail Filters
#If ALLOWED_FILE_EXTENSION is configured with no values then all files will be downloaded
ALLOWED_FILE_EXTENSION = 
PROHIBITED_FILE_EXTENSION = jpeg,jpg,tiff,gif,pdf,png
PROHIBITED_FILE_NAMES = 
PROHIBITED_MAIL_IDS = 

#Deatil Logging Needed
DETAIL_LOGGING_REQ = Y

#File Processing Confg.
EXECUTE_FILE_CONVERTER = Y
FILE_CONVERTER_PATH =/home/bznpwrusr/Desktop/Amway_Test/Amway_Czech/CRun.sh

