
# Root logger option
# log4j.rootLogger=INFO, TechLog, CustLog, myConsole
log4j.rootLogger=DEBUG, myConsole

#RollingFile Appender
log4j.appender.CustLog=org.apache.log4j.DailyRollingFileAppender
log4j.appender.CustLog.File=/home/bznpwrusr/Desktop/Amway_Test/Mail_Czech/Log/AuditLog.log
log4j.appender.CustLog.DatePattern='_'yyyy-MM-dd'.log'
log4j.appender.CustLog.layout=org.apache.log4j.PatternLayout
log4j.appender.CustLog.layout.ConversionPattern=%5p %d{dd MMM, yyyy HH:mm:ss} : %m%n

# Set the logger level of File Appender to INFO
log4j.category.CustLogLogger=INFO, CustLog
log4j.additivity.CustLog=false


#Console Appender
log4j.appender.myConsole=org.apache.log4j.ConsoleAppender
log4j.appender.myConsole.layout=org.apache.log4j.PatternLayout
log4j.appender.myConsole.layout.ConversionPattern=%5p %d{dd MMM, yyyy HH:mm:ss} (%F:%M %L) - %m%n


# Set the logger level of Console Appender to INFO
log4j.appender.myConsole.Threshold = DEBUG
log4j.additivity.myConsole=false

